### ISSUE TITLE
Overload Exception

### ISSUE THREAD

**Issue by IwraStudios** [akira-cn/js-expression#2]
`require("js-expression").Parser.parse("x*round(10 ^ -1)").evaluate({x:4});`

returns error:

TypeError: overload_192008565224423442.^(...) is not a function
    at eval (eval at toEvalFunction (G:\GeneralProjects\node-NumberObfuscator\node_modules\js-expression\parser.js:383:15), <anonymous>:3:53)
    at Object.evaluate (G:\GeneralProjects\node-NumberObfuscator\node_modules\js-expression\parser.js:404:17)
    at repl:1:59
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:340:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:538:10)

Do you know what the problem is?

**Comment by IwraStudios** [comment]
Actually I might, *might* have figured it out it takes the
`2*(10^-2) --> -1024 & 2*(10^(-2)) --> 0.02`
so with the direct - it interpreters it not as -(x) but as (^-) (x)
maybe I'm not quite sure
